export enum API_TAGS {
  USER = "USER",
  BRANCH = "BRANCH",
  DOUGHROOM = "DOUGHROOM",
  BAKERY = "BAKERY",
  NOTIFICATION = "NOTIFICATION",
  ORDER = "ORDER",
  MESSAGE = "MESSAGE",
  COMPLAINT = "COMPLAINT",
  INGRADIENT = "INGRADIENT",
  EXPENSE = "EXPENSE",
  REPORT = "REPORT",
  SALE = "SALE",
}

export const BAKERY_DOUGH_STATUS = {
  READY: "READY",
  PROGRESS: "PROGRESS",
  DELIVERED: "DELIVERED",
  DELIVERING: "DELIVERING",
  REDIRECTING: "REDIRECTING",
  DIVIDED: "DIVIDED",
  BAKED: "BAKED",
  SOLD: "SOLD",
};
