export enum PATHS {
  BAKERY = "/baker-room/get/",
  BAKERY_DOUGHES = "/dough/all-dough-bakerRoom/",
  DIVIDE = "/dough-ball/all-dough-ball/",
  SALARY = "/baker-room-salary/",
  DIVIDER = "/baker-room-salary/daily-worker-salary-baker-room/",
  ADD = "/add-divider",
  ADD_SALARY = "/add-divider-salary",
  BAKERY_BREADS = "/bakery/breads",
  BAKERY_DIVIDE = "/divide-dough-to-dough-balls",
  BAKERY_DIVIDE_UPDATE = "/edit-divide-dough-to-dough-balls",
  BAKERY_BAKE = "/bakery/bake",
  BAKERY_REDIRECT = "/baker-room-from-transferred-to-baker-room",
  DIVIDE_REDIRECT = "/dough-ball-transferred-to-baker-room",
}
